language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  # CI=false otherwise treat warnings as errors
  # see https://github.com/facebook/create-react-app/issues/3657
  # ("Treating warnings as errors because process.env.CI = true.")
  - CI=false npm run build
  - npm test -- --coverage
after_success:
  - npm run coveralls
